# Generated by Django 5.1.3 on 2024-11-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='deliveries_made',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='received_packages',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_sales',
        ),
    ]
