# Generated by Django 5.1.3 on 2024-11-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_salesdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesdata',
            table=None,
        ),
    ]
