# Generated by Django 5.1.3 on 2024-11-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_salesdata_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='month',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='salesdata',
            table='sales_data2',
        ),
    ]
